### ISSUE TITLE
golden-utils dependency

### ISSUE THREAD

**Issue by boogsbunny** [atlas-engineer/stripe#2]
Is this now a maintained fork? If so, then can the `golden-utils` dependency be replaced or mirrored? It's not on Quicklisp.

**Comment by aadcg** [comment]
@boogsbunny wouldn't it be more reasonable to add `golden-utils` to Quicklisp?

Edit: I think the issue you're raising is that `golden-utils` used to be hosted at https://github.com/mfiano/mfiano-utils but not anymore. I found a mirror at https://github.com/lisp-mirror/golden-utils.

**Comment by boogsbunny** [comment]
Oh wow. Yes, that would be easier. I didn't know that someone had a mirror, thanks!
