### ISSUE TITLE
upstream support

### ISSUE THREAD

**Issue by boogsbunny** [atlas-engineer/stripe#3]
It looks like Michael Fiano has stopped maintaining his lisp libraries. Would you consider taking over?

For example, the Quicklisp version doesn't have session support.

**Comment by aadcg** [comment]
@boogsbunny is this about `golden-utils`? I think https://github.com/lisp-mirror/golden-utils should be added to Quicklisp. 

Nonetheless, this seems not to be related to `stripe`.

**Comment by boogsbunny** [comment]
No, this is about stripe @aadcg. This package supports creating Stripe sessions. Mfiano's version on Quicklisp doesn't. He's not writing much lisp these days nor maintaining this package. He deleted all his repositories.

**Comment by boogsbunny** [comment]
I'm just wondering if you guys would take over maintaining this package since you've added endpoints like sessions?

**Comment by aadcg** [comment]
Sorry, I see your point now. I believe it would be OK, but @jmercouris would be the person to ask.

**Comment by boogsbunny** [comment]
What do you think @jmercouris?

**Comment by aadcg** [comment]
@boogsbunny we can maintain it.

**Comment by boogsbunny** [comment]
Awesome, thanks!

**Comment by aadcg** [comment]
I don't use quicklisp, but feel free to request adding this library.

**Comment by boogsbunny** [comment]
Requested updates to [quicklisp](https://github.com/quicklisp/quicklisp-projects/issues/2420) and [ocicl](https://github.com/ocicl/request-system-additions-here/issues/21)!

**Comment by boogsbunny** [comment]
The link in the awesome-cl repo has also been [updated](https://github.com/CodyReichert/awesome-cl/pull/496)!
