### ISSUE TITLE
switch json dependency from yason to com.inuoe.jzon

### ISSUE THREAD

**Issue by boogsbunny** [atlas-engineer/stripe#7]
It seems that these days [jzon](https://github.com/Zulu-Inuoe/jzon) is the [preferred json library](https://github.com/codyreichert/awesome-cl#json). What do you think about switching yason out for jzon?

**Comment by aadcg** [comment]
@boogsbunny I'd say that switching for its own sake may not be the best call here. If, however, there is a limitation in the current setting, then it can be considered.

**Comment by boogsbunny** [comment]
sounds good!

If that happens to be the case, then we can revisit this suggestion later on.
